# Image processing packages
import cv2
import skimage as ski
from skimage import io

# Data analysis packages
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# File management imports
import os
import sys
import glob
from pathlib import Path
import importlib

# # Importing functions from the .py files I created for AERIS analysis
import Preprocessing as preproc

#workshopping function to obtain crop parameters by rendering image:
def get_crop_params(frame:np.ndarray) -> dict:
    # conver to grayscale
    frame = preproc.frame_to_grayscale(frame)
    # display full frame
    plt.figure(figsize=(4,6))
    plt.imshow(frame, cmap ="gray")
    plt.title("Inspect and provide crop indices('left', 'right', 'top', 'bottom')\n Choose indices that center and leave empty space around the plates\nclose the window when ready to move on")
    plt.show()
    # Get initial coordinates:
    print("Enter coordinates")
    top = int(input("Top pixel value:"))
    bottom = int(input("Bottom pixel value:"))
    left = int(input("Left pixel value:"))
    right = int(input("Right pixel value:"))
    good_crop = False
    while not good_crop:
        cropped_frame = frame[top:bottom, left:right]
        plt.figure(figsize=(4,6))
        plt.imshow(cropped_frame, cmap = "gray")
        plt.title("Preview")
        plt.show()
        satisfied = input("Does the crop look good? (Y/N)")
        if satisfied.lower() == "y":
            good_crop = True
            crop_params = {"top": top,
                           "bottom": bottom,
                           "left": left,
                           "right": right}
            print("Saved crop parameters:", crop_params)
            plt.close()
        else:
            print("No problem, try again.")
            top = int(input("Top pixel value:"))
            bottom = int(input("Bottom pixel value:"))
            left = int(input("Left pixel value:"))
            right = int(input("Right pixel value:"))

    return crop_params




# IDENTIFYING FOLDER
parent_folder_str = "C:\\Users\\Gayatri\\Documents\\Graduate School\\01 Experiments\\HA project\\(07) Extensional rheology AutHTP\\MgCl2 variation"
parent_folder = Path(r"C:\Users\Gayatri\Documents\Graduate School\01 Experiments\HA project\(07) Extensional rheology AutHTP\MgCl2 variation")
dirs_list = os.listdir(parent_folder)

# list of the subfolders generated by PFV software
vid_folder_list = []
for f in dirs_list:
    p = parent_folder_str + "\\" + f
    p = Path(p)
    vid_folder_list.append(p)

fold_names = [f.name for f in vid_folder_list]  # List of folder names

# list of files  
filelst = []
for f in vid_folder_list[1:]:
    for v in f.glob("*mp4"):    # For all files rather than just the first
        filelst.append(v)

# list of the filenames
filenames = [f.name for f in filelst]

# FILE
# Open video - cv2
file_num = 18
cap = cv2.VideoCapture(filelst[file_num])
print(filenames[file_num])


col_rate = 1000   # in fps, actual collection rate
t_frame = (1/col_rate)*1000   # in ms, time interval of each frame.
print(f"{cap.get(cv2.CAP_PROP_FRAME_COUNT)} frames to process, {col_rate} fps")   # frame count. This is number of frames actually exported from the UX100
cap.release()

# EXTRACTING FRAMES - USING DURATION OF EXPERIMENT TO DECIDE STARTING FRAME

# open video
cap = cv2.VideoCapture(filelst[file_num])

expt_length = 8500 #ms - this is duration of experiment (how long we waited on AERIS before stopping video)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# Check if video was successfully opened:
if not cap.isOpened():
    print("Error: Could not open video file.")
else:
    print("Video file opened successfully!")

#set starting frame:
start_frame = total_frames - expt_length
cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)


imgs = []                                   # list of np.ndarrays to store frames
n = 4                                       # every nth frame to keep. Change to 1 if want all frames
fr_num = start_frame                        # setting frame number to the chosen start frame --- # DO I EVEN NEED THIS!?

# Extract each chosen frame into list.
while True:
    ret, frame = cap.read()
    if ret:
        if fr_num % n == 0:
            imgs.append(frame)
        fr_num +=1
    else:
        print(f"did not open frame {fr_num}")
        print(f"saved {len(imgs)} frames out of {fr_num} frames")
        break
    
cap.release()

# testing:
i = -1
frame = imgs[-1]
get_crop_params(frame)